version: 0.1
os: linux
files:
  - source: awesomeProject
    destination: /usr/local/bin/awesomeProject
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root