version: 0.2
env:
  variables:
    GOCACHE: "${CODEBUILD_SRC_DIR}/go-build"
phases:
  install:
    runtime-versions:
      golang: 1.22
  build:
    commands:
      - make build
artifacts:
  files:
    - awesomeProject