version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.22
  build:
    commands:
      - export GOCACHE=/tmp/gocache
      - make build
artifacts:
  files:
    - awesomeProject  # Your compiled binary
    - appspec.yml     # CodeDeploy configuration file
    - .env
  discard-paths: yes